/**
 * @file undistort.h
 * @brief Fast image undistortion using a pre-computed Look-Up Table (LUT).
 *
 * This class handles lens distortion correction for event-based cameras.
 * It parses camera calibration parameters (K matrix and distortion coefficients)
 * from a JSON file and populates a LUT to map distorted pixel coordinates
 * to rectified coordinates in constant time O(1).
 *
 * It supports standard OpenCV distortion models (Radial-Tangential).
 *
 * @author Vincenzo Polizzi - STARS Lab
 * @date Dec 27 2025
 */

#ifndef PROJECT_UNDISTORT_H
#define PROJECT_UNDISTORT_H

#include <vector>
#include <iostream>
#include <fstream>
#include <functional>
#include "json.hpp"
#include <opencv2/opencv.hpp>
#include <metavision/sdk/base/events/event_cd.h> // Ensure Metavision type definition is present

/**
 * @class Undistort
 * @brief Handles the rectification of 2D coordinates using calibration data.
 *
 * This class is optimized for high-speed event processing. Instead of calculating
 * the undistortion mapping for every single event (which involves expensive
 * trigonometric operations), it pre-calculates the mapping for every pixel
 * in the sensor during initialization. Subsequent undistortion calls are
 * simple memory lookups.
 */
class Undistort {
public:
    /**
     * @brief Constructor. Loads calibration and initializes the LUT.
     *
     * Parses the provided JSON file for camera intrinsics (K) and distortion coefficients (D).
     * If the file is missing or invalid, undistortion is disabled.
     *
     * @param filepath Path to the JSON calibration file (typically generated by Metavision/OpenCV).
     */
    explicit Undistort(const std::string &filepath) {
        std::vector<double> K, D;

        if (filepath.empty()) {
            std::cout << "\033[33m[Undistort] Warning: No calibration file provided. Passthrough mode enabled.\033[0m"
                      << std::endl;
            _is_calibrated = false;
            return;
        }
        _is_calibrated = true;

        parseFile(filepath, K, D);

        // Pre-allocate LUT memory
        _undistort_x.resize(_width * _height);
        _undistort_y.resize(_width * _height);

        if (K.empty() || D.empty()) {
            std::cout << "\033[33m[Undistort] Warning: K or D vectors are empty. Passthrough mode enabled.\033[0m" << std::endl;
            _is_calibrated = false;
            return;
        }

        // Convert std::vector to OpenCV Matrices
        cv::Mat K_mat = cv::Mat(3, 3, CV_64F, K.data());
        cv::Mat D_mat = cv::Mat(1, static_cast<int>(D.size()), CV_64F, D.data());

        // Populate the Look-Up Table (LUT)
        std::vector<cv::Point2f> distorted_points = {cv::Point2f(0, 0)};
        std::vector<cv::Point2f> undistorted_points;

        for (int y = 0; y < _height; ++y) {
            for (int x = 0; x < _width; ++x) {
                distorted_points[0].x = static_cast<float>(x);
                distorted_points[0].y = static_cast<float>(y);

                // OpenCV function to calculate rectified coordinates
                // Note: We use K_mat as the new camera matrix (P) to keep the image scale similar
                cv::undistortPoints(distorted_points, undistorted_points, K_mat, D_mat, cv::noArray(), K_mat);

                const int idx = y * _width + x;
                _undistort_x[idx] = static_cast<coords_type>(std::round(undistorted_points[0].x));
                _undistort_y[idx] = static_cast<coords_type>(std::round(undistorted_points[0].y));
            }
        }
    }

    /**
     * @brief Custom LUT population using a user-provided function.
     * * Useful if you have a non-standard distortion model not supported by OpenCV
     * but still want O(1) lookups.
     *
     * @param distortion A function taking (x, y) and returning undistorted (x', y').
     */
    void populate(const std::function<std::pair<double, double>(int, int)>& distortion) {
        if (!_is_calibrated) return;

        for (int y = 0; y < _height; ++y) {
            for (int x = 0; x < _width; ++x) {
                auto [x_undist, y_undist] = distortion(x, y);
                const int idx = y * _width + x;
                _undistort_x[idx] = static_cast<coords_type>(x_undist);
                _undistort_y[idx] = static_cast<coords_type>(y_undist);
            }
        }
    }

    /**
     * @brief Undistorts a pair of coordinates returning a pair.
     * @param x Input X coordinate.
     * @param y Input Y coordinate.
     * @return std::pair<unsigned short, unsigned short> The rectified coordinates.
     */
    std::pair<unsigned short, unsigned short> operator()(int x, int y) const {
        if (!_is_calibrated) {
            return {static_cast<unsigned short>(x), static_cast<unsigned short>(y)};
        }
        // Boundary check (optional for speed, but good for safety)
        if (x < 0 || x >= _width || y < 0 || y >= _height) {
            return {static_cast<unsigned short>(x), static_cast<unsigned short>(y)};
        }

        const auto idx = y * _width + x;
        return {_undistort_x[idx], _undistort_y[idx]};
    }

    /**
     * @brief Undistorts coordinates in-place via references.
     * * This overload is often faster as it avoids creating std::pair objects.
     *
     * @param x Input X coordinate.
     * @param y Input Y coordinate.
     * @param[out] new_x Output rectified X coordinate.
     * @param[out] new_y Output rectified Y coordinate.
     */
    void operator()(unsigned short x, unsigned short y, unsigned short &new_x, unsigned short &new_y) {
        if (!_is_calibrated) {
            new_x = x;
            new_y = y;
            return;
        }

        // Fast path: trust the caller to provide valid coordinates
        // or add bounds checking if segmentation faults occur.
        const auto idx = y * _width + x;
        new_x = _undistort_x[idx];
        new_y = _undistort_y[idx];
    }

    /**
     * @brief Undistorts a Metavision EventCD object.
     * * Returns a new event with the same timestamp and polarity, but rectified coordinates.
     *
     * @param ev Input raw event.
     * @return Metavision::EventCD Rectified event.
     */
    Metavision::EventCD operator()(const Metavision::EventCD &ev) const {
        if (!_is_calibrated) { return ev; }

        const auto idx = ev.y * _width + ev.x;
        return {
                _undistort_x[idx],
                _undistort_y[idx],
                ev.p,
                ev.t
        };
    }

    /** @return The width of the sensor in pixels. */
    int getWidth() const { return _width; }

    /** @return The height of the sensor in pixels. */
    int getHeight() const { return _height; }

private:
    using coords_type = unsigned short;

    /// Lookup table for X coordinates
    std::vector<coords_type> _undistort_x;
    /// Lookup table for Y coordinates
    std::vector<coords_type> _undistort_y;

    int _width = 0;
    int _height = 0;
    bool _is_calibrated = false;

    /**
     * @brief Helper to parse the JSON calibration file.
     * @param filepath Path to file.
     * @param[out] K Camera matrix vector (flat).
     * @param[out] D Distortion coefficients vector.
     */
    void parseFile(const std::string &filepath, std::vector<double> &K, std::vector<double> &D) {
        try {
            std::ifstream file(filepath.c_str());
            if (!file.is_open()) {
                std::cerr << "[Undistort] Error: Failed to open " << filepath << std::endl;
                _is_calibrated = false;
                return;
            }

            auto data = nlohmann::json::parse(file);

            auto img_size = data["image_size"];
            _width = img_size[0];
            _height = img_size[1];

            K = data["camera_matrix"]["data"].get<std::vector<double>>();
            D = data["distortion_coefficients"]["data"].get<std::vector<double>>();

            std::cout << "[Undistort] Loaded Calibration:" << std::endl;
            std::cout << "  Image Size: " << _width << "x" << _height << std::endl;
            std::cout << "  Camera Matrix (K): [";
            for (size_t i = 0; i < K.size(); i++) std::cout << K[i] << (i < K.size()-1 ? ", " : "");
            std::cout << "]" << std::endl;

        } catch (const std::exception &e) {
            std::cerr << "[Undistort] JSON Parsing Error: " << e.what() << std::endl;
            _is_calibrated = false;
        }
    }
};

#endif //PROJECT_UNDISTORT_H